/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formqldl;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author ADMIN
 */
public class quanly extends javax.swing.JFrame {

   // public int currentRecordIndex;

    /**
     * Creates new form quanly
     */
    public quanly() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        First = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Last = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        AddNew = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Pre = new javax.swing.JButton();
        Masv = new javax.swing.JTextField();
        Hoten = new javax.swing.JTextField();
        Malop = new javax.swing.JTextField();
        Ngaysinh = new javax.swing.JTextField();
        Gioitinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Mã sinh viên");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Mã lớp");

        jLabel5.setText("Giới tính");

        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Last.setText("Last");
        Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        AddNew.setText("AddNew");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });

        Next.setText("Next");
        Next.setName("Next"); // NOI18N
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Pre.setText("Pre");
        Pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreActionPerformed(evt);
            }
        });

        Masv.setName("Masv"); // NOI18N
        Masv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasvActionPerformed(evt);
            }
        });

        Hoten.setName("Hoten"); // NOI18N

        Malop.setName("Malop"); // NOI18N

        Ngaysinh.setName("Ngaysinh"); // NOI18N

        Gioitinh.setName("Gioitinh"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(Ngaysinh))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(Hoten))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addComponent(Masv, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Last)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddNew))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(First)
                            .addGap(97, 97, 97)
                            .addComponent(Pre))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Malop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 47, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Delete)
                                            .addComponent(Update))
                                        .addGap(58, 58, 58))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Edit)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Next)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(Cancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(Masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(Malop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(Pre)
                    .addComponent(First)
                    .addComponent(Delete))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNew)
                    .addComponent(Last)
                    .addComponent(Edit)
                    .addComponent(Update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
     // int currentRecordIndex = 0;
    public Connection con = null;
    public ResultSet rs;
    public int Chucnang=0;
    public void Hienthi() throws SQLException{
        try{
            Masv.setText(rs.getString("Masv"));
            Hoten.setText(rs.getString("Hoten"));
            Ngaysinh.setText(rs.getString("Ngaysinh"));
            Gioitinh.setText(rs.getString("Gioitinh"));
            Malop.setText(rs.getString("Malop"));
            Update.setEnabled(false);
            Cancel.setEnabled(false);

        }catch(Exception e){
            System.err.println("co loi"+e.getMessage());
        }
    }
    public void Resetdata()throws SQLException{
        java.sql.Statement st= con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        String SqlString ="Select * from Sinhvien";
        rs=st.executeQuery(SqlString);
        rs.next();
    }
// nút delete
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
 try {
        // Lấy mã sinh viên hiện tại
        String masv = Masv.getText();

        // Xóa bản ghi hiện tại từ cơ sở dữ liệu
        java.sql.Statement st = con.createStatement();
        String sql = "DELETE FROM Sinhvien WHERE Masv='" + masv + "'";
        st.executeUpdate(sql);

        // Di chuyển đến bản ghi tiếp theo (nếu có)
        if (rs.next()) {
            Hienthi();
        } else {
            // Nếu không còn bản ghi nào, bạn có thể xóa trắng các TextField hoặc thực hiện điều gì đó khác
            Masv.setText("");
            Hoten.setText("");
            Ngaysinh.setText("");
            Gioitinh.setText("");
            Malop.setText("");
        }
        Delete.setEnabled(false);
        

    } catch (Exception e) {
        e.printStackTrace();
        // Xử lý lỗi ở đây nếu cần
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa bản ghi!");
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.isFirst())
                Hienthi();
            Next.setEnabled(true);
            Pre.setEnabled(false);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_FirstActionPerformed

    private void LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.isLast())
                Hienthi();
            Next.setEnabled(false);
            Pre.setEnabled(true);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_LastActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        try{
            String username ="sa";
            String password="123456789";
            String url="jdbc:sqlserver://localhost:1433;databaseName=Quanlysinhvien;encrypt=false;";
      Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        con = java.sql.DriverManager.getConnection(url, username, password);
        System.out.println("Da ket noi");

            java.sql.Statement st= con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sqlString = "Select *From Sinhvien";
            rs = st.executeQuery(sqlString);

            if (rs.next()) {
                Hienthi();
            } else {
                Masv.setText("");
                Hoten.setText("");
                Ngaysinh.setText("");
                Gioitinh.setText("");
               Malop.setText("");
            }}
//      
          catch (ClassNotFoundException | SQLException e) {
           e.printStackTrace();
        }
   
    }//GEN-LAST:event_formWindowActivated
 
    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
     
        Masv.setText("");
        Hoten.setText("");
        Ngaysinh.setText("");
        Gioitinh.setText("");
        Malop.setText("");
        Masv.setEnabled(true);
        Hoten.setEnabled(true);
        Ngaysinh.setEnabled(true);
        Gioitinh.setEnabled(true);
        Malop.setEnabled(true);
        AddNew.setEnabled(false);
        Edit.setEnabled(false);
        Update.setEnabled(true);
        Cancel.setEnabled(true);
        Chucnang=1; 
        //JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
    }//GEN-LAST:event_AddNewActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        String masv = Masv.getText();
        String hoten = Hoten.getText();
        String ngaysinh = Ngaysinh.getText();
        String gioitinh = Gioitinh.getText();
        String malop = Malop.getText();
     
        Masv.setEnabled(true);
        Hoten.setEnabled(true);
        Ngaysinh.setEnabled(true);
        Gioitinh.setEnabled(true);
        Malop.setEnabled(true);
        AddNew.setEnabled(false);
        Edit.setEnabled(false);
        Update.setEnabled(true);
        Cancel.setEnabled(true);
        Chucnang=2;
    }//GEN-LAST:event_EditActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

try {
     
            java.sql.Statement st=con.createStatement();
            String sqlString="";
               if (Chucnang == 1)  {
            sqlString = "INSERT INTO Sinhvien(Masv, Hoten, Ngaysinh, Gioitinh, Malop) VALUES ('"+Masv.getText()+"','"+Hoten.getText()+"','"+
                   Ngaysinh.getText()+"','"+Gioitinh.getText()+"','"+Malop.getText()+"')";
      
                st.executeUpdate(sqlString);
               Update.setEnabled(false);
               Cancel.setEnabled(false);

               }
               if (Chucnang == 2) {
             sqlString = "UPDATE Sinhvien SET Hoten='"+Hoten.getText()+"', Ngaysinh='"+Ngaysinh.getText()+"',Gioitinh='"+Gioitinh.getText()+"',Malop='"+Malop.getText()+
                     "' Where Masv='"+Masv.getText()+"'";

                st.executeUpdate(sqlString);
          Update.setEnabled(false);
           Cancel.setEnabled(false);
        AddNew.setEnabled(true);
        Edit.setEnabled(true);
              
    }  
       JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
     
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu!");
    
}

    }//GEN-LAST:event_UpdateActionPerformed

    private void MasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasvActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
     
               Masv.setEnabled(true);
        Hoten.setEnabled(true);
        Ngaysinh.setEnabled(true);
        Gioitinh.setEnabled(true);
        Malop.setEnabled(true);
        AddNew.setEnabled(true);
        Edit.setEnabled(true);
        Update.setEnabled(false);
        Cancel.setEnabled(false);

    }//GEN-LAST:event_CancelActionPerformed

    private void PreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreActionPerformed
     
    try {
            
            
            if (rs != null && rs.previous()) {
                Hienthi();
                Next.setEnabled(true);
            } 
            if(rs.isFirst()){
                    Pre.setEnabled(false);
                
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }


        
    }//GEN-LAST:event_PreActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed

          try {
            Pre.setEnabled(true);
            
            if (rs != null && rs.next()) {
                Hienthi();
                Pre.setEnabled(true);
            } 
            if(rs.isLast()){
                Next.setEnabled(false);
              

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton First;
    private javax.swing.JTextField Gioitinh;
    private javax.swing.JTextField Hoten;
    private javax.swing.JButton Last;
    private javax.swing.JTextField Malop;
    private javax.swing.JTextField Masv;
    private javax.swing.JButton Next;
    private javax.swing.JTextField Ngaysinh;
    private javax.swing.JButton Pre;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
